### ISSUE TITLE
Not fetching any Post

### ISSUE THREAD

**Issue by ishandutta2007** [contentful/blog-app-android#2]
I have set delivery credentials,
published my posts in contentful.
but vault.fetch(Post.class).all() here https://github.com/contentful/blog-app-android/blob/master/app/src/main/java/blog/contentful/loaders/PostListLoader.java#L21
is always returning blank array.

**Comment by ishandutta2007** [comment]
Resolved it myself.
I was using the preview API access token instead of the production API access token.
Still it would be better if someone clarifies which token to us when, before closing the ticket.

**Comment by mariobodemann** [comment]
Hey Mario from Contentful here,

as long as no one calls [`.preview()`](https://contentful.github.io/contentful.java/com/contentful/java/cda/CDAClient.Builder.html#preview--) in the [`CDAClient`](https://contentful.github.io/contentful.java/com/contentful/java/cda/CDAClient.html) building process, we always take the production API access token. 

If you would like to change that in this demo app, you would need to add the `.preview()` call just before
[the builder builds the client](
https://github.com/contentful/blog-app-android/blob/master/app/src/main/java/blog/contentful/lib/ClientProvider.java#L27).

Greetings,
Mario

**Comment by ishandutta2007** [comment]
Thanks
